package com.exercise.irrigation.models;
// Generated May 12, 2023, 10:02:58 AM by Hibernate Tools 6.0.0.Alpha2

import jakarta.persistence.*;

/**
 * Plot generated by hbm2java
 */
@Entity
@Table(name="plot"
    ,catalog="irrigation_system"
    , uniqueConstraints = @UniqueConstraint(columnNames="name") 
)
public class Plot  implements java.io.Serializable {


     private Integer id;
     private TimeSlot timeSlot;
     private String name;
     private double area;
     private double waterRequired;
     private String cropType;

    public Plot() {
    }

	
    public Plot(String name, double area, double waterRequired, String cropType) {
        this.name = name;
        this.area = area;
        this.waterRequired = waterRequired;
        this.cropType = cropType;
    }
    public Plot(TimeSlot timeSlot, String name, double area, double waterRequired, String cropType) {
       this.timeSlot = timeSlot;
       this.name = name;
       this.area = area;
       this.waterRequired = waterRequired;
       this.cropType = cropType;
    }
   
     @Id @GeneratedValue

    
    @Column(name="ID", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="time_slot_id")
    public TimeSlot getTimeSlot() {
        return this.timeSlot;
    }
    
    public void setTimeSlot(TimeSlot timeSlot) {
        this.timeSlot = timeSlot;
    }

    
    @Column(name="name", unique=true, nullable=false, length=50)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="area", nullable=false, precision=22, scale=0)
    public double getArea() {
        return this.area;
    }
    
    public void setArea(double area) {
        this.area = area;
    }

    
    @Column(name="water_required", nullable=false, precision=22, scale=0)
    public double getWaterRequired() {
        return this.waterRequired;
    }
    
    public void setWaterRequired(double waterRequired) {
        this.waterRequired = waterRequired;
    }

    
    @Column(name="crop_type", nullable=false, length=50)
    public String getCropType() {
        return this.cropType;
    }
    
    public void setCropType(String cropType) {
        this.cropType = cropType;
    }




}


